"""
jmcore - Core library for JoinMarket components

Provides shared functionality for protocol, crypto, and networking.
"""

# Bitcoin utilities - consolidated from multiple modules
from jmcore.bitcoin import (
    ParsedTransaction,
    TxInput,
    TxOutput,
    address_to_scriptpubkey,
    create_p2wpkh_script_code,
    decode_varint,
    encode_varint,
    get_hrp,
    get_txid,
    hash160,
    hash256,
    parse_transaction,
    parse_transaction_bytes,
    pubkey_to_p2wpkh_address,
    pubkey_to_p2wpkh_script,
    script_to_p2wsh_address,
    script_to_p2wsh_scriptpubkey,
    scriptpubkey_to_address,
    serialize_outpoint,
    serialize_transaction,
    sha256,
)
from jmcore.btc_script import BondAddressInfo, derive_bond_address
from jmcore.commitment_blacklist import (
    COMMITMENT_HEX_LENGTH,
    CommitmentBlacklist,
    add_commitment,
    check_and_add_commitment,
    check_commitment,
    get_blacklist,
    set_blacklist_path,
    validate_commitment_hex,
)
from jmcore.config import (
    BackendConfig,
    DirectoryServerConfig,
    TorConfig,
    TorControlConfig,
    WalletConfig,
)
from jmcore.constants import (
    BITCOIN_DUST_THRESHOLD,
    DEFAULT_DUST_THRESHOLD,
    DUST_THRESHOLD,
    SECP256K1_N,
    SECP256K1_P,
    STANDARD_DUST_LIMIT,
)
from jmcore.deduplication import (
    DeduplicationStats,
    MessageDeduplicator,
    ResponseDeduplicator,
)
from jmcore.directory_client import (
    DirectoryClient,
    DirectoryClientError,
    OfferWithTimestamp,
)
from jmcore.encryption import CryptoSession, NaclError
from jmcore.models import (
    DIRECTORY_NODES_MAINNET,
    DIRECTORY_NODES_SIGNET,
    DIRECTORY_NODES_TESTNET,
    MessageEnvelope,
    PeerInfo,
    calculate_cj_fee,
    get_default_directory_nodes,
)
from jmcore.nick_tracker import NickTracker
from jmcore.notifications import (
    NotificationConfig,
    NotificationPriority,
    Notifier,
    convert_settings_to_notification_config,
    get_notifier,
    load_notification_config,
    reset_notifier,
)
from jmcore.paths import (
    get_all_nick_states,
    get_commitment_blacklist_path,
    get_default_data_dir,
    get_ignored_makers_path,
    get_nick_state_path,
    read_nick_state,
    remove_nick_state,
    write_nick_state,
)
from jmcore.podle import (
    PoDLECommitment,
    PoDLEError,
    deserialize_revelation,
    generate_podle,
    parse_podle_revelation,
    serialize_revelation,
    verify_podle,
)
from jmcore.protocol import (
    FEATURE_NEUTRINO_COMPAT,
    FEATURE_PUSH_ENCRYPTED,
    JM_VERSION,
    JM_VERSION_MIN,
    FeatureSet,
    MessageType,
    ProtocolMessage,
    RequiredFeatures,
    UTXOMetadata,
    format_utxo_list,
    get_nick_version,
    parse_utxo_list,
    peer_supports_neutrino_compat,
)
from jmcore.rate_limiter import RateLimiter, TokenBucket
from jmcore.settings import (
    DEFAULT_DIRECTORY_SERVERS,
    BitcoinSettings,
    DirectoryServerSettings,
    JoinMarketSettings,
    LoggingSettings,
    MakerSettings,
    NetworkSettings,
    NotificationSettings,
    OrderbookWatcherSettings,
    TakerSettings,
    TorSettings,
    WalletSettings,
    config_diff,
    ensure_config_file,
    generate_config_template,
    get_config_path,
    get_settings,
    reset_settings,
)
from jmcore.tasks import parse_directory_address, run_periodic_task
from jmcore.timenumber import (
    TIMELOCK_EPOCH,
    TIMELOCK_EPOCH_TIMESTAMP,
    TIMELOCK_EPOCH_YEAR,
    TIMELOCK_ERA_YEARS,
    TIMENUMBER_COUNT,
    format_locktime_date,
    get_all_locktimes,
    get_all_timenumbers,
    get_future_locktimes,
    get_nearest_valid_locktime,
    is_valid_locktime,
    parse_locktime_date,
    timenumber_to_timestamp,
    timestamp_to_timenumber,
    validate_locktime,
)
from jmcore.tor_control import (
    EphemeralHiddenService,
    HiddenServiceDoSConfig,
    TorAuthenticationError,
    TorCapabilities,
    TorControlClient,
    TorControlError,
    TorHiddenServiceError,
)
from jmcore.tor_isolation import (
    IsolationCategory,
    IsolationCredentials,
    NormalizedProxyURL,
    build_isolated_proxy_url,
    get_isolation_credentials,
    normalize_proxy_url,
)
from jmcore.version import (
    VERSION,
    UpdateCheckResult,
    __version__,
    check_for_updates_from_github,
    get_version,
    get_version_info,
    get_version_tuple,
)

__all__ = [
    # Version
    "VERSION",
    "__version__",
    "UpdateCheckResult",
    "check_for_updates_from_github",
    "get_version",
    "get_version_info",
    "get_version_tuple",
    # Constants
    "BITCOIN_DUST_THRESHOLD",
    "DEFAULT_DUST_THRESHOLD",
    "DUST_THRESHOLD",
    "SECP256K1_N",
    "SECP256K1_P",
    "STANDARD_DUST_LIMIT",
    # Deduplication
    "DeduplicationStats",
    "MessageDeduplicator",
    "ResponseDeduplicator",
    # Config
    "BackendConfig",
    "DirectoryServerConfig",
    "TorConfig",
    "TorControlConfig",
    "WalletConfig",
    # Commitment blacklist
    "COMMITMENT_HEX_LENGTH",
    "CommitmentBlacklist",
    "add_commitment",
    "check_and_add_commitment",
    "check_commitment",
    "get_blacklist",
    "set_blacklist_path",
    "validate_commitment_hex",
    # Encryption
    "CryptoSession",
    "NaclError",
    # Directory
    "DIRECTORY_NODES_MAINNET",
    "DIRECTORY_NODES_SIGNET",
    "DIRECTORY_NODES_TESTNET",
    "DirectoryClient",
    "DirectoryClientError",
    "OfferWithTimestamp",
    "get_default_directory_nodes",
    # Models
    "MessageEnvelope",
    "PeerInfo",
    "calculate_cj_fee",
    # Nick tracking
    "NickTracker",
    # Notifications
    "NotificationConfig",
    "NotificationPriority",
    "Notifier",
    "convert_settings_to_notification_config",
    "get_notifier",
    "load_notification_config",
    "reset_notifier",
    # Paths
    "get_all_nick_states",
    "get_commitment_blacklist_path",
    "get_default_data_dir",
    "get_ignored_makers_path",
    "get_nick_state_path",
    "read_nick_state",
    "remove_nick_state",
    "write_nick_state",
    # PoDLE
    "PoDLECommitment",
    "PoDLEError",
    "deserialize_revelation",
    "generate_podle",
    "parse_podle_revelation",
    "serialize_revelation",
    "verify_podle",
    # Protocol
    "FEATURE_NEUTRINO_COMPAT",
    "FEATURE_PUSH_ENCRYPTED",
    "FeatureSet",
    "JM_VERSION",
    "JM_VERSION_MIN",
    "MessageType",
    "ProtocolMessage",
    "RequiredFeatures",
    "UTXOMetadata",
    "format_utxo_list",
    "get_nick_version",
    "parse_utxo_list",
    "peer_supports_neutrino_compat",
    # Rate limiting
    "RateLimiter",
    "TokenBucket",
    # Tor
    "EphemeralHiddenService",
    "HiddenServiceDoSConfig",
    "TorAuthenticationError",
    "TorCapabilities",
    "TorControlClient",
    "TorControlError",
    "TorHiddenServiceError",
    # Tor stream isolation
    "IsolationCategory",
    "IsolationCredentials",
    "NormalizedProxyURL",
    "build_isolated_proxy_url",
    "get_isolation_credentials",
    "normalize_proxy_url",
    # Timenumber (fidelity bonds)
    "TIMENUMBER_COUNT",
    "TIMELOCK_EPOCH",
    "TIMELOCK_EPOCH_TIMESTAMP",
    "TIMELOCK_EPOCH_YEAR",
    "TIMELOCK_ERA_YEARS",
    "format_locktime_date",
    "get_all_locktimes",
    "get_all_timenumbers",
    "get_future_locktimes",
    "get_nearest_valid_locktime",
    "is_valid_locktime",
    "parse_locktime_date",
    "timenumber_to_timestamp",
    "timestamp_to_timenumber",
    "validate_locktime",
    # Bitcoin utilities (consolidated)
    "ParsedTransaction",
    "TxInput",
    "TxOutput",
    "address_to_scriptpubkey",
    "create_p2wpkh_script_code",
    "decode_varint",
    "encode_varint",
    "get_hrp",
    "get_txid",
    "hash160",
    "hash256",
    "parse_transaction",
    "parse_transaction_bytes",
    "pubkey_to_p2wpkh_address",
    "pubkey_to_p2wpkh_script",
    "script_to_p2wsh_address",
    "script_to_p2wsh_scriptpubkey",
    "scriptpubkey_to_address",
    "serialize_outpoint",
    "serialize_transaction",
    "sha256",
    # Bond utilities
    "BondAddressInfo",
    "derive_bond_address",
    # Tasks
    "parse_directory_address",
    "run_periodic_task",
    # Settings
    "BitcoinSettings",
    "DEFAULT_DIRECTORY_SERVERS",
    "DirectoryServerSettings",
    "JoinMarketSettings",
    "LoggingSettings",
    "MakerSettings",
    "NetworkSettings",
    "NotificationSettings",
    "OrderbookWatcherSettings",
    "TakerSettings",
    "TorSettings",
    "WalletSettings",
    "ensure_config_file",
    "config_diff",
    "generate_config_template",
    "get_config_path",
    "get_settings",
    "reset_settings",
]
