#!/usr/bin/env bash
# =============================================================================
# JoinMarket NG Local Release Build Script
#
# Builds Docker images locally and generates a release manifest with layer
# digests. This enables a "local-first" release workflow where the signer
# builds and signs before CI, rather than waiting for CI to finish.
#
# The manifest produced is identical in format to the one generated by CI.
# CI will independently verify its layer digests match the signed manifest.
#
# Usage:
#   ./scripts/build-release.sh <version>
#   ./scripts/build-release.sh              # Auto-detect from version.py
#
# Requirements:
#   - docker with buildx (docker-container driver)
#   - jq
#   - git
#
# Output:
#   release-manifest-<version>.txt in the project root directory
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

usage() {
    cat << EOF
Usage: $(basename "$0") [version] [options]

Build Docker images locally and generate a release manifest.

This script builds all release images for your current architecture and
produces a manifest file with layer digests. Use this before sign-release.sh
for a local-first release workflow:

  1. bump_version.py patch --no-push    # bump version, create tag locally
  2. build-release.sh                   # build images, generate manifest
  3. sign-release.sh --manifest <file>  # sign the locally-built manifest
  4. git push && git push --tags        # push tag to trigger CI

CI will then build the same images and verify digests match the signed manifest.

Arguments:
  version         Release version (e.g., 1.0.0)
                  If omitted, reads from jmcore/src/jmcore/version.py

Options:
  --help          Show this help message

Examples:
  $(basename "$0")                    # Use version from version.py
  $(basename "$0") 1.0.0             # Explicit version
EOF
    exit 1
}

# Detect current architecture in Docker format
detect_arch() {
    local arch
    arch=$(uname -m)
    case "$arch" in
        x86_64)  echo "amd64" ;;
        aarch64) echo "arm64" ;;
        armv7l)  echo "arm-v7" ;;
        *)       echo "$arch" ;;
    esac
}

# Check/setup buildx builder with docker-container driver for OCI export support
setup_buildx_builder() {
    local builder_name="jmng-verify"

    local current_driver
    current_driver=$(docker buildx inspect 2>/dev/null | awk '/^Driver:/{print $2}')

    if [[ "$current_driver" == "docker-container" ]]; then
        return 0
    fi

    if docker buildx inspect "$builder_name" &>/dev/null; then
        docker buildx use "$builder_name" >/dev/null 2>&1
        log_info "Using buildx builder: $builder_name"
        return 0
    fi

    log_info "Creating buildx builder with docker-container driver..."
    if docker buildx create --name "$builder_name" --driver docker-container --bootstrap; then
        docker buildx use "$builder_name"
        log_info "Created and activated buildx builder: $builder_name"
        return 0
    else
        log_error "Failed to create buildx builder."
        log_error "You can manually create one with:"
        log_error "  docker buildx create --name $builder_name --driver docker-container --use"
        return 1
    fi
}

# Parse arguments
VERSION=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --help|-h)
            usage
            ;;
        *)
            if [[ -z "$VERSION" ]]; then
                VERSION="$1"
            else
                log_error "Unknown argument: $1"
                usage
            fi
            shift
            ;;
    esac
done

# Auto-detect version from version.py if not specified
if [[ -z "$VERSION" ]]; then
    VERSION=$(grep -oP '__version__\s*=\s*"\K[^"]+' "$PROJECT_ROOT/jmcore/src/jmcore/version.py")
    if [[ -z "$VERSION" ]]; then
        log_error "Could not detect version from jmcore/src/jmcore/version.py"
        exit 1
    fi
    log_info "Auto-detected version: $VERSION"
fi

# Check prerequisites
if ! command -v jq &> /dev/null; then
    log_error "jq is required. Please install it."
    exit 1
fi

if ! command -v docker &> /dev/null; then
    log_error "docker is required. Please install it."
    exit 1
fi

# Ensure buildx builder supports OCI export
if ! setup_buildx_builder; then
    exit 1
fi

# Detect current architecture
CURRENT_ARCH=$(detect_arch)
case "$CURRENT_ARCH" in
    amd64)  PLATFORM="linux/amd64" ;;
    arm64)  PLATFORM="linux/arm64" ;;
    arm-v7) PLATFORM="linux/arm/v7" ;;
    *)
        log_error "Unsupported architecture: $CURRENT_ARCH"
        exit 1
        ;;
esac

# Get commit and SOURCE_DATE_EPOCH from the current HEAD
COMMIT_SHA=$(git -C "$PROJECT_ROOT" rev-parse HEAD)
SOURCE_DATE_EPOCH=$(git -C "$PROJECT_ROOT" log -1 --pretty=%ct)
BUILD_DATE=$(date -u -d "@$SOURCE_DATE_EPOCH" +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || \
             date -u -r "$SOURCE_DATE_EPOCH" +"%Y-%m-%dT%H:%M:%SZ")

log_info "Building JoinMarket NG release $VERSION"
log_info "Commit: $COMMIT_SHA"
log_info "SOURCE_DATE_EPOCH: $SOURCE_DATE_EPOCH"
log_info "Platform: $PLATFORM ($CURRENT_ARCH)"
echo ""

# Create temp directory for build artifacts
WORK_DIR=$(mktemp -d)
trap "rm -rf '$WORK_DIR'" EXIT

# Images and their corresponding targets (must match CI workflow matrix)
IMAGES=("directory-server" "directory-server-debug" "maker" "taker" "orderbook-watcher" "jmwalletd" "jam-ng")
DOCKERFILES=("./directory_server/Dockerfile" "./directory_server/Dockerfile" "./maker/Dockerfile" "./taker/Dockerfile" "./orderbook_watcher/Dockerfile" "./jmwalletd/Dockerfile" "./jmwalletd/Dockerfile")
TARGETS=("production" "debug" "" "" "" "jmwalletd" "jam-ng")

# Create OCI output directory
OCI_DIR="$WORK_DIR/oci"
DIGEST_DIR="$WORK_DIR/digests"
mkdir -p "$OCI_DIR" "$DIGEST_DIR"

BUILD_ERRORS=0

for i in "${!IMAGES[@]}"; do
    image="${IMAGES[$i]}"
    dockerfile="${DOCKERFILES[$i]}"
    target="${TARGETS[$i]}"

    log_info "Building $image for $PLATFORM..."

    OCI_TAR="$OCI_DIR/${image}.tar"
    OCI_EXTRACT="$OCI_DIR/${image}"
    mkdir -p "$OCI_EXTRACT"

    # Build command with optional --target
    BUILD_CMD=(docker buildx build
        --file "$dockerfile"
        --build-arg SOURCE_DATE_EPOCH="$SOURCE_DATE_EPOCH"
        --build-arg VERSION="$VERSION"
        --platform "$PLATFORM"
        --output "type=oci,dest=${OCI_TAR},rewrite-timestamp=true"
        --no-cache)
    if [[ -n "$target" ]]; then
        BUILD_CMD+=(--target "$target")
    fi

    if ! SOURCE_DATE_EPOCH="$SOURCE_DATE_EPOCH" "${BUILD_CMD[@]}" \
        "$PROJECT_ROOT" 2>&1 | tee "$WORK_DIR/${image}-build.log"; then
        log_error "  Build failed for $image"
        BUILD_ERRORS=$((BUILD_ERRORS + 1))
        continue
    fi

    # Extract OCI tar and get layer digests
    tar -xf "$OCI_TAR" -C "$OCI_EXTRACT"

    # Get the manifest digest from OCI index.json
    manifest_digest=$(jq -r '.manifests[0].digest' "$OCI_EXTRACT/index.json")
    manifest_file="$OCI_EXTRACT/blobs/sha256/${manifest_digest#sha256:}"

    # Extract layer digests from the manifest
    jq -r '.layers[].digest' "$manifest_file" | sort > "$DIGEST_DIR/${image}-${CURRENT_ARCH}-layers.txt"

    layer_count=$(wc -l < "$DIGEST_DIR/${image}-${CURRENT_ARCH}-layers.txt")
    log_info "  Built successfully ($layer_count layers)"

    # Clean up OCI files to save disk space
    rm -rf "$OCI_TAR" "$OCI_EXTRACT"
done

echo ""

if [[ $BUILD_ERRORS -gt 0 ]]; then
    log_error "$BUILD_ERRORS image(s) failed to build!"
    exit 1
fi

log_info "All images built successfully!"

# =============================================================================
# Generate release manifest (same format as CI)
# =============================================================================
MANIFEST_FILE="$PROJECT_ROOT/release-manifest-${VERSION}.txt"

log_info "Generating release manifest: $MANIFEST_FILE"

cat > "$MANIFEST_FILE" << EOF
# JoinMarket NG Release Manifest
# Version: ${VERSION}
# Commit: ${COMMIT_SHA}
# Build Date: ${BUILD_DATE}
# SOURCE_DATE_EPOCH: ${SOURCE_DATE_EPOCH}
#
# This manifest contains layer digests for reproducible build verification.
# Layer digests are content-addressable hashes of the actual image layers,
# which are identical regardless of manifest format (Docker vs OCI).
#
# Verification instructions: see technical/development docs

## Git Commit
commit: ${COMMIT_SHA}
source_date_epoch: ${SOURCE_DATE_EPOCH}

## Docker Images

## Per-Platform Layer Digests (for reproducibility verification)
EOF

# Add layer digests per platform (sorted by filename for deterministic order)
for digest_file in $(ls "$DIGEST_DIR"/*-layers.txt 2>/dev/null | sort); do
    if [ -f "$digest_file" ]; then
        image_name=$(basename "$digest_file" .txt)
        echo "" >> "$MANIFEST_FILE"
        echo "### ${image_name}" >> "$MANIFEST_FILE"
        cat "$digest_file" >> "$MANIFEST_FILE"
    fi
done

echo ""
log_info "Release manifest generated!"
echo ""
cat "$MANIFEST_FILE"
echo ""

echo "=============================================="
log_info "Build Complete!"
echo "=============================================="
echo ""
echo "Manifest file: $MANIFEST_FILE"
echo "Architecture:  $CURRENT_ARCH (layer digests for this platform only)"
echo ""
echo "Next steps:"
echo "  1. Sign the manifest:"
echo "     ./scripts/sign-release.sh $VERSION --manifest $MANIFEST_FILE --key <fingerprint>"
echo ""
echo "  2. Push the tag to trigger CI:"
echo "     git push && git push --tags"
echo ""
echo "  CI will build for all platforms and verify its layer digests match."
echo "  The manifest will be uploaded to the GitHub Release by CI."
