#!/usr/bin/env bash
# =============================================================================
# JoinMarket NG Local Release Build Script
#
# Builds Docker images locally and generates a release manifest with layer
# digests. This enables a "local-first" release workflow where the signer
# builds and signs before CI, rather than waiting for CI to finish.
#
# The manifest produced is identical in format to the one generated by CI.
# CI will independently verify its layer digests match the signed manifest.
#
# Usage:
#   ./scripts/build-release.sh <version>
#   ./scripts/build-release.sh              # Auto-detect from version.py
#
# Requirements:
#   - docker with buildx (docker-container driver)
#   - jq
#   - git
#
# Output:
#   release-manifest-<version>.txt in the project root directory
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

usage() {
    cat << EOF
Usage: $(basename "$0") [version] [options]

Build Docker images locally and generate a release manifest.

This script builds all release images for your current architecture and
produces a manifest file with layer digests. Use this before sign-release.sh
for a local-first release workflow:

  1. bump_version.py patch --no-push    # bump version, create tag locally
  2. build-release.sh                   # build images, generate manifest
  3. sign-release.sh --manifest <file>  # sign the locally-built manifest
  4. git push && git push --tags        # push tag to trigger CI

CI will then build the same images and verify digests match the signed manifest.

Arguments:
  version         Release version (e.g., 1.0.0)
                  If omitted, reads from jmcore/src/jmcore/version.py

Options:
  --jobs, -j <n>  Maximum parallel image builds
                  Default: number of CPU cores on this machine
  --help          Show this help message

Examples:
  $(basename "$0")                    # Use version from version.py
  $(basename "$0") --jobs 4           # Build with 4 parallel jobs
  $(basename "$0") 1.0.0             # Explicit version
EOF
    exit 1
}

detect_cpu_cores() {
    if command -v nproc &> /dev/null; then
        nproc
        return 0
    fi

    if command -v getconf &> /dev/null; then
        getconf _NPROCESSORS_ONLN
        return 0
    fi

    if command -v sysctl &> /dev/null; then
        sysctl -n hw.ncpu
        return 0
    fi

    echo "1"
}

# Detect current architecture in Docker format
detect_arch() {
    local arch
    arch=$(uname -m)
    case "$arch" in
        x86_64)  echo "amd64" ;;
        aarch64) echo "arm64" ;;
        armv7l)  echo "arm-v7" ;;
        *)       echo "$arch" ;;
    esac
}

# Check/setup buildx builder with docker-container driver for OCI export support
setup_buildx_builder() {
    local builder_name="jmng-verify"

    local current_driver
    current_driver=$(docker buildx inspect 2>/dev/null | awk '/^Driver:/{print $2}')

    if [[ "$current_driver" == "docker-container" ]]; then
        return 0
    fi

    if docker buildx inspect "$builder_name" &>/dev/null; then
        docker buildx use "$builder_name" >/dev/null 2>&1
        log_info "Using buildx builder: $builder_name"
        return 0
    fi

    log_info "Creating buildx builder with docker-container driver..."
    if docker buildx create --name "$builder_name" --driver docker-container --bootstrap; then
        docker buildx use "$builder_name"
        log_info "Created and activated buildx builder: $builder_name"
        return 0
    else
        log_error "Failed to create buildx builder."
        log_error "You can manually create one with:"
        log_error "  docker buildx create --name $builder_name --driver docker-container --use"
        return 1
    fi
}

# Parse arguments
VERSION=""
BUILD_JOBS=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --help|-h)
            usage
            ;;
        --jobs|-j)
            if [[ $# -lt 2 ]]; then
                log_error "Missing value for $1"
                usage
            fi
            BUILD_JOBS="$2"
            shift 2
            ;;
        --jobs=*|-j=*)
            BUILD_JOBS="${1#*=}"
            shift
            ;;
        -* )
            log_error "Unknown option: $1"
            usage
            ;;
        *)
            if [[ -z "$VERSION" ]]; then
                VERSION="$1"
                shift
            else
                log_error "Unknown argument: $1"
                usage
            fi
            ;;
    esac
done

# Auto-detect version from version.py if not specified
if [[ -z "$VERSION" ]]; then
    VERSION=$(grep -oP '__version__\s*=\s*"\K[^"]+' "$PROJECT_ROOT/jmcore/src/jmcore/version.py")
    if [[ -z "$VERSION" ]]; then
        log_error "Could not detect version from jmcore/src/jmcore/version.py"
        exit 1
    fi
    log_info "Auto-detected version: $VERSION"
fi

if [[ -z "$BUILD_JOBS" ]]; then
    BUILD_JOBS=$(detect_cpu_cores)
fi

if ! [[ "$BUILD_JOBS" =~ ^[0-9]+$ ]] || [[ "$BUILD_JOBS" -lt 1 ]]; then
    log_error "Invalid value for --jobs: $BUILD_JOBS (must be an integer >= 1)"
    exit 1
fi

# Check prerequisites
if ! command -v jq &> /dev/null; then
    log_error "jq is required. Please install it."
    exit 1
fi

if ! command -v docker &> /dev/null; then
    log_error "docker is required. Please install it."
    exit 1
fi

# Ensure buildx builder supports OCI export
if ! setup_buildx_builder; then
    exit 1
fi

# Detect current architecture
CURRENT_ARCH=$(detect_arch)
case "$CURRENT_ARCH" in
    amd64)  PLATFORM="linux/amd64" ;;
    arm64)  PLATFORM="linux/arm64" ;;
    arm-v7) PLATFORM="linux/arm/v7" ;;
    *)
        log_error "Unsupported architecture: $CURRENT_ARCH"
        exit 1
        ;;
esac

# Get commit and SOURCE_DATE_EPOCH from the current HEAD
COMMIT_SHA=$(git -C "$PROJECT_ROOT" rev-parse HEAD)
SOURCE_DATE_EPOCH=$(git -C "$PROJECT_ROOT" log -1 --pretty=%ct)
BUILD_DATE=$(date -u -d "@$SOURCE_DATE_EPOCH" +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || \
             date -u -r "$SOURCE_DATE_EPOCH" +"%Y-%m-%dT%H:%M:%SZ")

# Resolve build ref to mirror CI's ${{ github.ref_name }}.
# On a tag push CI sets ref_name to the tag (e.g. "v0.28.0"); on a branch push it
# is the branch name. Locally we prefer a tag pointing at HEAD (release workflow),
# falling back to the current branch. This must match the value setup.py would
# otherwise derive itself, so the produced /root/.local layer is byte-identical
# to CI's. setup.py reads JOINMARKET_BUILD_COMMIT/REF before falling back to git,
# so passing them explicitly also makes the build reproducible inside the docker
# build sandbox where the .git directory is not available.
BUILD_REF=$(git -C "$PROJECT_ROOT" tag --points-at HEAD | head -n 1)
if [[ -z "$BUILD_REF" ]]; then
    BUILD_REF=$(git -C "$PROJECT_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
    if [[ "$BUILD_REF" == "HEAD" ]]; then
        BUILD_REF=""
    fi
fi

log_info "Building JoinMarket NG release $VERSION"
log_info "Commit: $COMMIT_SHA"
log_info "Build ref: ${BUILD_REF:-<none>}"
log_info "SOURCE_DATE_EPOCH: $SOURCE_DATE_EPOCH"
log_info "Platform: $PLATFORM ($CURRENT_ARCH)"
log_info "Parallel jobs: $BUILD_JOBS"
echo ""

# Create temp directory for build artifacts
WORK_DIR=$(mktemp -d)
trap "rm -rf '$WORK_DIR'" EXIT

# Images and their corresponding targets (must match CI workflow matrix)
IMAGES=("directory-server" "directory-server-debug" "maker" "taker" "orderbook-watcher" "jmwalletd" "jam-ng")
DOCKERFILES=("./directory_server/Dockerfile" "./directory_server/Dockerfile" "./maker/Dockerfile" "./taker/Dockerfile" "./orderbook_watcher/Dockerfile" "./jmwalletd/Dockerfile" "./jmwalletd/Dockerfile")
TARGETS=("production" "debug" "" "" "" "jmwalletd" "jam-ng")

# Create OCI output directory
OCI_DIR="$WORK_DIR/oci"
DIGEST_DIR="$WORK_DIR/digests"
mkdir -p "$OCI_DIR" "$DIGEST_DIR"

BUILD_ERRORS=0

build_image() {
    local image="$1"
    local dockerfile="$2"
    local target="$3"

    local oci_tar="$OCI_DIR/${image}.tar"
    local oci_extract="$OCI_DIR/${image}"
    local manifest_digest
    local manifest_file
    local -a build_cmd

    mkdir -p "$oci_extract"

    # Build command with optional --target
    # JOINMARKET_BUILD_COMMIT/REF are stamped into wheel metadata via setup.py.
    # Mirroring CI's release.yaml ensures the resulting /root/.local COPY layer
    # has the same digest locally and in CI (reproducible build verification).
    build_cmd=(docker buildx build
        --file "$dockerfile"
        --build-arg SOURCE_DATE_EPOCH="$SOURCE_DATE_EPOCH"
        --build-arg VERSION="$VERSION"
        --build-arg JOINMARKET_BUILD_COMMIT="$COMMIT_SHA"
        --build-arg JOINMARKET_BUILD_REF="$BUILD_REF"
        --platform "$PLATFORM"
        --output "type=oci,dest=${oci_tar},rewrite-timestamp=true"
        --no-cache)
    if [[ -n "$target" ]]; then
        build_cmd+=(--target "$target")
    fi

    if ! SOURCE_DATE_EPOCH="$SOURCE_DATE_EPOCH" "${build_cmd[@]}" \
        "$PROJECT_ROOT" > "$WORK_DIR/${image}-build.log" 2>&1; then
        return 1
    fi

    # Extract OCI tar and get layer digests
    tar -xf "$oci_tar" -C "$oci_extract"

    # Get the manifest digest from OCI index.json
    manifest_digest=$(jq -r '.manifests[0].digest' "$oci_extract/index.json")
    manifest_file="$oci_extract/blobs/sha256/${manifest_digest#sha256:}"

    # Extract layer digests from the manifest
    jq -r '.layers[].digest' "$manifest_file" | sort > "$DIGEST_DIR/${image}-${CURRENT_ARCH}-layers.txt"

    # Clean up OCI files to save disk space
    rm -rf "$oci_tar" "$oci_extract"
}

declare -a BUILD_PIDS=()
declare -A PID_TO_IMAGE=()

remove_pid_from_queue() {
    local completed_pid="$1"
    local -a remaining_pids=()
    local queued_pid

    for queued_pid in "${BUILD_PIDS[@]}"; do
        if [[ "$queued_pid" != "$completed_pid" ]]; then
            remaining_pids+=("$queued_pid")
        fi
    done

    BUILD_PIDS=("${remaining_pids[@]}")
}

collect_build_result() {
    local pid="$1"
    local status="$2"
    local image="${PID_TO_IMAGE[$pid]}"

    if [[ "$status" -eq 0 ]]; then
        layer_count=$(wc -l < "$DIGEST_DIR/${image}-${CURRENT_ARCH}-layers.txt")
        log_info "  $image built successfully ($layer_count layers)"
    else
        log_error "  Build failed for $image (log: $WORK_DIR/${image}-build.log)"
        BUILD_ERRORS=$((BUILD_ERRORS + 1))
    fi

    unset 'PID_TO_IMAGE[$pid]'
    remove_pid_from_queue "$pid"
}

wait_for_next_build() {
    local completed_pid=""
    local wait_status=0

    if wait -n -p completed_pid "${BUILD_PIDS[@]}"; then
        wait_status=0
    else
        wait_status=$?
    fi

    if [[ -z "$completed_pid" ]]; then
        log_error "Failed to determine which build process completed."
        BUILD_ERRORS=$((BUILD_ERRORS + 1))
        return
    fi

    collect_build_result "$completed_pid" "$wait_status"
}

for i in "${!IMAGES[@]}"; do
    image="${IMAGES[$i]}"
    dockerfile="${DOCKERFILES[$i]}"
    target="${TARGETS[$i]}"

    log_info "Building $image for $PLATFORM in parallel..."
    build_image "$image" "$dockerfile" "$target" &
    pid=$!
    BUILD_PIDS+=("$pid")
    PID_TO_IMAGE["$pid"]="$image"

    if [[ ${#BUILD_PIDS[@]} -ge "$BUILD_JOBS" ]]; then
        wait_for_next_build
    fi
done

while [[ ${#BUILD_PIDS[@]} -gt 0 ]]; do
    wait_for_next_build
done

echo ""

if [[ $BUILD_ERRORS -gt 0 ]]; then
    log_error "$BUILD_ERRORS image(s) failed to build!"
    exit 1
fi

log_info "All images built successfully!"

# =============================================================================
# Generate release manifest (same format as CI)
# =============================================================================
MANIFEST_FILE="$PROJECT_ROOT/release-manifest-${VERSION}.txt"

log_info "Generating release manifest: $MANIFEST_FILE"

{
    printf '# JoinMarket NG Release Manifest\n'
    printf '# Version: %s\n' "$VERSION"
    printf '# Commit: %s\n' "$COMMIT_SHA"
    printf '# Build Date: %s\n' "$BUILD_DATE"
    printf '# SOURCE_DATE_EPOCH: %s\n' "$SOURCE_DATE_EPOCH"
    printf '#\n'
    printf '# This manifest contains layer digests for reproducible build verification.\n'
    printf '# Layer digests are content-addressable hashes of the actual image layers,\n'
    printf '# which are identical regardless of manifest format (Docker vs OCI).\n'
    printf '#\n'
    printf '# Verification instructions: see technical/development docs\n'
    printf '\n'
    printf '## Git Commit\n'
    printf 'commit: %s\n' "$COMMIT_SHA"
    printf 'source_date_epoch: %s\n' "$SOURCE_DATE_EPOCH"
    printf '\n'
    printf '## Docker Images\n'
    printf '\n'
    printf '## Per-Platform Layer Digests (for reproducibility verification)\n'
} > "$MANIFEST_FILE"

# Add layer digests per platform (sorted by filename for deterministic order)
for digest_file in $(ls "$DIGEST_DIR"/*-layers.txt 2>/dev/null | sort); do
    if [ -f "$digest_file" ]; then
        image_name=$(basename "$digest_file" .txt)
        echo "" >> "$MANIFEST_FILE"
        echo "### ${image_name}" >> "$MANIFEST_FILE"
        cat "$digest_file" >> "$MANIFEST_FILE"
    fi
done

echo ""
log_info "Release manifest generated!"
echo ""
cat "$MANIFEST_FILE"
echo ""

echo "=============================================="
log_info "Build Complete!"
echo "=============================================="
echo ""
echo "Manifest file: $MANIFEST_FILE"
echo "Architecture:  $CURRENT_ARCH (layer digests for this platform only)"
echo ""
echo "Next steps:"
echo "  1. Sign the manifest:"
echo "     ./scripts/sign-release.sh $VERSION --manifest $MANIFEST_FILE --key <fingerprint>"
echo ""
echo "  2. Push the tag to trigger CI:"
echo "     git push && git push --tags"
echo ""
echo "  CI will build for all platforms and verify its layer digests match."
echo "  The manifest will be uploaded to the GitHub Release by CI."
